[book]
authors = ["PC Gao"]
language = "zh-CN"
src = "src"
title = "PCGao's Blog"
description = "个人项目、技术博客与闲谈"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/PC-Gao/PC-Gao.github.io"
edit-url-template = "https://github.com/PC-Gao/PC-Gao.github.io/edit/master/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/page-toc.js", "theme/giscus.js"]
site-url = "/"
sidebar-header-nav = false

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true
limit-results = 15
